# Generated by Django 5.0 on 2023-12-28 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=1500)),
                ('stock', models.PositiveBigIntegerField(blank=True, default=0, help_text='Cantidad que tiene disponible', validators=[django.core.validators.MinValueValidator(0)])),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='El precio del producto.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(blank=True, max_length=75)),
                ('imagen', models.ImageField(blank=True, upload_to='media/img_productos')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
