# Generated by Django 5.0 on 2023-12-31 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_imagen_alter_productos_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.PositiveBigIntegerField(default=0, error_messages={'min_value': '<div class="alert alert-danger" role="alert">A simple danger alert—check it out!</div>'}, help_text='Cantidad que tiene disponible', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
